# Generated by Django 5.0.1 on 2024-01-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0002_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterField(
            model_name='store',
            name='books',
            field=models.ManyToManyField(related_name='stores', to='bookshop.book'),
        ),
    ]
