# Generated by Django 5.0.1 on 2024-01-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='start_date',
            field=models.DateField(),
        ),
    ]
