# Generated by Django 5.0.1 on 2024-01-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_speciality_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='degree',
            field=models.CharField(choices=[('master', 'Master'), ('bachelor', 'Bachelor'), ('academic', 'Academic'), ('drscience', 'DrScience'), ('phs', 'PhD')], max_length=9),
        ),
    ]
